# Generated by Django 5.1.4 on 2025-01-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_door_descriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='perm_level',
            field=models.IntegerField(choices=[(0, 'Permission level 0'), (1, 'Permission level 1'), (2, 'Permission level 2'), (3, 'Permission level 3'), (4, 'Permission level 4'), (5, 'Permission level 5')]),
        ),
        migrations.AlterField(
            model_name='permission',
            name='perm_level',
            field=models.IntegerField(choices=[(0, 'Permission level 0'), (1, 'Permission level 1'), (2, 'Permission level 2'), (3, 'Permission level 3'), (4, 'Permission level 4'), (5, 'Permission level 5')]),
        ),
    ]
