# Generated by Django 5.1.4 on 2025-01-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_door_perm_level_alter_permission_perm_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='descriptor',
            field=models.CharField(default='Door description', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='door',
            name='perm_level',
            field=models.IntegerField(choices=[(0, 'Level 0 - Guest'), (1, 'Level 1 - Employee'), (2, 'Level 2 - Specialist'), (3, 'Level 3 - Deputy Manager'), (4, 'Level 4 - Manager'), (5, 'Level 5 - Director')]),
        ),
        migrations.AlterField(
            model_name='permission',
            name='perm_level',
            field=models.IntegerField(choices=[(0, 'Level 0 - Guest'), (1, 'Level 1 - Employee'), (2, 'Level 2 - Specialist'), (3, 'Level 3 - Deputy Manager'), (4, 'Level 4 - Manager'), (5, 'Level 5 - Director')]),
        ),
    ]
